/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_Cliente;

import Capa_Negocio.Participante;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jefer
 */
public class FrmListaPorUniversidadYTipoDeAlumno extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmConsultarParticipantesInscritos
     */
    public FrmListaPorUniversidadYTipoDeAlumno() {
        initComponents();
        setTitle("Lista de participantes");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboUniversidadProcedencia = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cboTipoParticipante = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatosGeneral = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Universidad de procedencia:");

        cboUniversidadProcedencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USAT", "UNPRG", "UTP", "UMB", "UDL", "USS" }));

        jLabel2.setText("Tipo de participante:");

        cboTipoParticipante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pregrado", "Posgrado" }));

        tblDatosGeneral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblDatosGeneral);

        jButton1.setText("Listar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cboUniversidadProcedencia, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cboTipoParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(227, 227, 227))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboUniversidadProcedencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cboTipoParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel modelo = new DefaultTableModel();
        String univProcedencia = cboUniversidadProcedencia.getSelectedItem().toString();
        String tipoParticipante = cboTipoParticipante.getSelectedItem().toString();
        
        modelo.addColumn("Nombre");
        modelo.addColumn("Sexo");
        modelo.addColumn("Modalidad");
        modelo.addColumn("Universidad");
        modelo.addColumn("Costo");
        
        Object datos[] = new Object [5];
        
        ArrayList lista = Participante.consultarParticipantesInscritos(univProcedencia, tipoParticipante);
        
        for (int i = 0; i < lista.size(); i++) {
            Participante objParticipante = (Participante) lista.get(i);
            datos[0]=objParticipante.getNombre();
            datos[1]=objParticipante.getSexo();
            datos[2]=objParticipante.getTipoParticipante();
            datos[3]=objParticipante.getUnivProcedencia();
            datos[4]=objParticipante.getCostoParticipante();
            modelo.addRow(datos);
        }
        tblDatosGeneral.setModel(modelo);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboTipoParticipante;
    private javax.swing.JComboBox<String> cboUniversidadProcedencia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDatosGeneral;
    // End of variables declaration//GEN-END:variables
}
