package Capa_Cliente;

import Capa_Datos.LineaBelleza_Atendidos;
import Capa_Datos.LineaBelleza_Normal;
import Capa_Datos.LineaSalud_Atendidos;
import Capa_Datos.LineaSalud_Normal;
import Capa_Negocio.Cliente;
import TColas.TCola;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

public class Frm_AtenderCliente extends javax.swing.JInternalFrame {

    public Frm_AtenderCliente() {
        initComponents();
        btnAtender.setEnabled(false);
        txtNombre.setEditable(false);
        txtDNI.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboLinea = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDate = new com.toedter.calendar.JDateChooser();
        txtMonto = new javax.swing.JTextField();
        btnAtender = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnVerCliente = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Atender Cliente");

        jLabel1.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        jLabel2.setText("Elegir Linea:");

        cboLinea.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        cboLinea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Seleccionar---", "Salud-bienestar", "Belleza" }));

        jLabel3.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        jLabel3.setText("DNI:");

        txtNombre.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N

        txtDNI.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        jLabel4.setText("Fecha de compra:");

        jLabel5.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        jLabel5.setText("Monto de compra:");

        txtDate.setDateFormatString("dd/MM/yyyy");
        txtDate.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N

        txtMonto.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N

        btnAtender.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        btnAtender.setText("Atender");
        btnAtender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtenderActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnVerCliente.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        btnVerCliente.setText("Ver cliente");
        btnVerCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(btnAtender)
                .addGap(83, 83, 83)
                .addComponent(btnVolver)
                .addContainerGap(147, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDNI, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboLinea, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMonto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVerCliente)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerCliente))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtender)
                    .addComponent(btnVolver))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenderActionPerformed
        try {
            Cliente objCli = null;
            String linea = cboLinea.getSelectedItem().toString();
            float monto = Float.parseFloat(txtMonto.getText());
//            Date fecha = txtDate.getDate();
            int año = txtDate.getCalendar().get(Calendar.YEAR);
            int mes = txtDate.getCalendar().get(Calendar.MONTH) + 1;
            int dia = txtDate.getCalendar().get(Calendar.DATE);
            if (cboLinea.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Por favor, seleccionar línea de productos", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                if (monto <= 0) {
                    JOptionPane.showMessageDialog(this, "Por favor, ingresar monto válido", "ERROR", JOptionPane.ERROR_MESSAGE);
                } else {
                    if (linea.equalsIgnoreCase("Salud-bienestar")) {
                        TCola LSN = LineaSalud_Normal.consultar();
                        TCola LSA = LineaSalud_Atendidos.consultar();
                        objCli = (Cliente) LSN.Eliminar();
                        objCli.setMonto(monto);
                        objCli.setAño(año);
                        objCli.setMes(mes);
                        objCli.setDia(dia);
                        LSA.Insertar(objCli);
                    } else {
                        TCola LBN = LineaBelleza_Normal.consultar();
                        TCola LBA = LineaBelleza_Atendidos.consultar();
                        objCli = (Cliente) LBN.Eliminar();
                        objCli.setMonto(monto);
                        objCli.setAño(año);
                        objCli.setMes(mes);
                        objCli.setDia(dia);
                        LBA.Insertar(objCli);

                    }
                }
            }
            txtMonto.setText("");
            txtNombre.setText("");
            txtDNI.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error inesperado: " + e.getLocalizedMessage(), "ERROR DEL SISTEMA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAtenderActionPerformed

    private void btnVerClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerClienteActionPerformed
        try {
            Cliente objCli = null;
            String linea = cboLinea.getSelectedItem().toString();
            if (cboLinea.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Por favor, seleccionar línea de productos", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                if (linea.equalsIgnoreCase("Salud-bienestar")) {
                    TCola LSN = LineaSalud_Normal.consultar();
                    if (!LSN.Vacia()) {
                        objCli = (Cliente) LSN.Primero();
                        txtNombre.setText(objCli.getNombre());
                        txtDNI.setText(objCli.getDni());
                        btnAtender.setEnabled(true);
                    } else {
                        JOptionPane.showMessageDialog(this, "Cola vacía", "ERROR", JOptionPane.ERROR_MESSAGE);
                        btnAtender.setEnabled(false);
                    }
                } else {
                    TCola LBN = LineaBelleza_Normal.consultar();
                    if (!LBN.Vacia()) {
                        objCli = (Cliente) LBN.Primero();
                        txtNombre.setText(objCli.getNombre());
                        txtDNI.setText(objCli.getDni());
                        btnAtender.setEnabled(true);
                    } else {
                        JOptionPane.showMessageDialog(this, "Cola vacía", "ERROR", JOptionPane.ERROR_MESSAGE);
                        btnAtender.setEnabled(false);
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error inesperado: " + e.getLocalizedMessage(), "ERROR DEL SISTEMA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnVerClienteActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtender;
    private javax.swing.JButton btnVerCliente;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cboLinea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtDNI;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
