/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cliente;

import javax.swing.JFrame;

/**
 *
 * @author laboratorio_computo
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal() {
        initComponents();
        setTitle("Menú principal");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuRegistrarCombustible = new javax.swing.JMenuItem();
        mnuGestionarDispensadores = new javax.swing.JMenuItem();
        mnuRegistrarDispensador = new javax.swing.JMenuItem();
        mnuListarCombustibles = new javax.swing.JMenuItem();
        mnuListarDispensadores = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuRegistrarCliente = new javax.swing.JMenuItem();
        mnuRegistrarVenta = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu1.setText("Mantenimiento");

        mnuRegistrarCombustible.setText("Gestionar combustible");
        mnuRegistrarCombustible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegistrarCombustibleActionPerformed(evt);
            }
        });
        jMenu1.add(mnuRegistrarCombustible);

        mnuGestionarDispensadores.setText("Gestionar trabajador");
        mnuGestionarDispensadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGestionarDispensadoresActionPerformed(evt);
            }
        });
        jMenu1.add(mnuGestionarDispensadores);

        mnuRegistrarDispensador.setText("Gestionar dispensador");
        mnuRegistrarDispensador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegistrarDispensadorActionPerformed(evt);
            }
        });
        jMenu1.add(mnuRegistrarDispensador);

        mnuListarCombustibles.setText("Listar combustibles");
        jMenu1.add(mnuListarCombustibles);

        mnuListarDispensadores.setText("Listar dispensadores");
        jMenu1.add(mnuListarDispensadores);

        jMenuItem1.setText("Listar trabajadores");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Operaciones");

        mnuRegistrarCliente.setText("Registrar cliente");
        jMenu2.add(mnuRegistrarCliente);

        mnuRegistrarVenta.setText("Registrar venta");
        jMenu2.add(mnuRegistrarVenta);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Reportes");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Acerca De");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuRegistrarCombustibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegistrarCombustibleActionPerformed
        GestionarCombustible obj = new GestionarCombustible();
        panel.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_mnuRegistrarCombustibleActionPerformed

    private void mnuRegistrarDispensadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegistrarDispensadorActionPerformed
        GestionarDispensador obj = new GestionarDispensador();
        panel.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_mnuRegistrarDispensadorActionPerformed

    private void mnuGestionarDispensadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGestionarDispensadoresActionPerformed
        GestionarTrabajador obj = new GestionarTrabajador();
        panel.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_mnuGestionarDispensadoresActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem mnuGestionarDispensadores;
    private javax.swing.JMenuItem mnuListarCombustibles;
    private javax.swing.JMenuItem mnuListarDispensadores;
    private javax.swing.JMenuItem mnuRegistrarCliente;
    private javax.swing.JMenuItem mnuRegistrarCombustible;
    private javax.swing.JMenuItem mnuRegistrarDispensador;
    private javax.swing.JMenuItem mnuRegistrarVenta;
    public static javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
