/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Cliente;

import Datos.Lista_Dispensadores;
import Datos.Lista_Trabajadores;
import Logica.Dispensador;
import Logica.Trabajador;
import TListas.TLista;
import javax.swing.JOptionPane;

/**
 *
 * @author jefer
 */
public class FrmRegistrarDispensador extends javax.swing.JInternalFrame {

    TLista LT = Lista_Trabajadores.consultar();

    public FrmRegistrarDispensador() {
        initComponents();
        for (int i = 0; i < LT.Cantidad(); i++) {
            Trabajador obj = (Trabajador) LT.Obtener(i);
            cboCodigo.addItem(String.valueOf(obj.getCodigo()));
        }
        if (LT.Vacia()) {
            JOptionPane.showMessageDialog(rootPane, "No hay trabajadores registrados", "AVISO", 2);
        }
        btnRegistrar.setEnabled(false);
    }
    
    public void habilitarBtnRegistrar(){
        String numD = txtNumDisp.getText();
        String numC = txtNumComb.getText();
        if (numD.length()==1 & numC.length()==1 & !LT.Vacia()) {
            btnRegistrar.setEnabled(true);
        } else {
            btnRegistrar.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboCodigo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtNumDisp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNumComb = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Registrar dispensador");

        jLabel1.setText("Código de trabajador:");

        jLabel2.setText("N° dispensador:");

        txtNumDisp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumDispKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumDispKeyTyped(evt);
            }
        });

        jLabel3.setText("N° combustibles:");

        txtNumComb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumCombKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumCombKeyTyped(evt);
            }
        });

        jLabel4.setText("Estado:");

        txtEstado.setText("HÁBIL");
        txtEstado.setEnabled(false);

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboCodigo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumComb, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(24, 24, 24)
                        .addComponent(txtNumDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumDisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumComb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        Lista_Dispensadores LD = new Lista_Dispensadores();
        int numDisp = Integer.parseInt(txtNumDisp.getText());
        int pos = LD.buscarNumDisp(numDisp);

        if (pos != -1) {
            JOptionPane.showMessageDialog(rootPane, "Este dispensador ya está registrado", "ERROR", 2);
        } else {
            Dispensador obj = new Dispensador();

            obj.setCodigoTrabajador(Integer.parseInt(cboCodigo.getSelectedItem().toString()));
            obj.setNumero(Integer.parseInt(txtNumDisp.getText()));
            obj.setNumeroCombustibles(Integer.parseInt(txtNumComb.getText()));
            obj.setEstado(txtEstado.getText());

            Lista_Dispensadores.adicionar(obj);
            JOptionPane.showMessageDialog(rootPane, "Dispensador registrado", "En horabuena", 1);
            cboCodigo.setSelectedIndex(0);
            txtNumDisp.setText("");
            txtNumComb.setText("");
            txtEstado.setText("");
            
            btnRegistrar.setEnabled(false);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtNumDispKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDispKeyTyped
        char c = evt.getKeyChar();

        if ((c < '0' | c > '9') | txtNumDisp.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNumDispKeyTyped

    private void txtNumCombKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumCombKeyTyped
        char c = evt.getKeyChar();

        if ((c < '0' | c > '9') | txtNumComb.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNumCombKeyTyped

    private void txtNumDispKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDispKeyReleased
        habilitarBtnRegistrar();
    }//GEN-LAST:event_txtNumDispKeyReleased

    private void txtNumCombKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumCombKeyReleased
        habilitarBtnRegistrar();
    }//GEN-LAST:event_txtNumCombKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cboCodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNumComb;
    private javax.swing.JTextField txtNumDisp;
    // End of variables declaration//GEN-END:variables
}
