/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Cliente;

import Datos.*;
import Lógica.Cliente;
import TColas.*;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author jefer
 */
public class FrmAtenderClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmAtenderClientes
     */
    public FrmAtenderClientes() {
        initComponents();
        btnAtender.setEnabled(false);
        btnCalcularMonto.setEnabled(false);
    }

    public void habilitarBtn3puntos() {
        if (txtEntradas.getText().length() > 0) {
            btnCalcularMonto.setEnabled(true);
        } else {
            btnCalcularMonto.setEnabled(false);
        }
    }

    public FrmAtenderClientes(JButton btnAtender, JButton btnCalcularMonto, JButton btnVerCliente, JComboBox<String> cboTipoCola, JLabel jLabel1, JLabel jLabel2, JLabel jLabel4, JLabel jLabel6, JLabel jLabel7, JLabel lblMonto, JLabel lblNombre, JLabel lblTarjeta, JTextField txtEntradas) {
        this.btnAtender = btnAtender;
        this.btnCalcularMonto = btnCalcularMonto;
        this.btnVerCliente = btnVerCliente;
        this.cboTipoCola = cboTipoCola;
        this.jLabel1 = jLabel1;
        this.jLabel2 = jLabel2;
        this.jLabel4 = jLabel4;
        this.jLabel6 = jLabel6;
        this.jLabel7 = jLabel7;
        this.lblMonto = lblMonto;
        this.lblNombre = lblNombre;
        this.lblTarjeta = lblTarjeta;
        this.txtEntradas = txtEntradas;
    }

    public void habilitarBtnAtender() {
        if (txtEntradas.getText().length() > 0) {
            btnAtender.setEnabled(true);
        } else {
            btnAtender.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboTipoCola = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTarjeta = new javax.swing.JLabel();
        btnVerCliente = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtEntradas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        btnCalcularMonto = new javax.swing.JButton();
        btnAtender = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 0, 0));
        setClosable(true);
        setTitle("Atender Clientes");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Elegir cola:");

        cboTipoCola.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cola de clientes (normal)", "Cola de clientes con tarjeta" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("?????????????");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo de tarjeta:");

        lblTarjeta.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblTarjeta.setForeground(new java.awt.Color(255, 255, 255));
        lblTarjeta.setText("?????????????");

        btnVerCliente.setBackground(new java.awt.Color(0, 0, 0));
        btnVerCliente.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        btnVerCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnVerCliente.setText("Ver cliente");
        btnVerCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerClienteActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("N° de entradas:");

        txtEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntradasActionPerformed(evt);
            }
        });
        txtEntradas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEntradasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEntradasKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Monto a pagar:");

        lblMonto.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblMonto.setForeground(new java.awt.Color(255, 255, 255));
        lblMonto.setText("??????");

        btnCalcularMonto.setBackground(new java.awt.Color(0, 0, 0));
        btnCalcularMonto.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcularMonto.setText("...");
        btnCalcularMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularMontoActionPerformed(evt);
            }
        });

        btnAtender.setBackground(new java.awt.Color(0, 0, 0));
        btnAtender.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnAtender.setForeground(new java.awt.Color(255, 255, 255));
        btnAtender.setText("ATENDER");
        btnAtender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMonto)
                        .addGap(18, 18, 18)
                        .addComponent(btnCalcularMonto))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTarjeta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVerCliente))
                            .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboTipoCola, 0, 225, Short.MAX_VALUE))))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAtender)
                .addGap(169, 169, 169))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboTipoCola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblNombre))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblTarjeta)
                    .addComponent(btnVerCliente))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(lblMonto)
                    .addComponent(btnCalcularMonto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnAtender)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularMontoActionPerformed
        int numEntradas = Integer.parseInt(txtEntradas.getText());
        if (numEntradas != 0) {
            float monto = numEntradas * 15;
            lblMonto.setText(String.valueOf(monto));
        } else {
            JOptionPane.showMessageDialog(rootPane, "Ingrese una cantidad válida");
        }

    }//GEN-LAST:event_btnCalcularMontoActionPerformed

    private void btnAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenderActionPerformed
        Cliente obj = null;
        if (lblMonto.getText().equalsIgnoreCase("??????") && lblNombre.getText().equalsIgnoreCase("?????????????")) {
            JOptionPane.showMessageDialog(rootPane, "Intente nuevamente");
        } else {
            if (cboTipoCola.getSelectedIndex() == 0) {
                TCola CCST = ColaClientesST.consultar();
                txtEntradas.requestFocus();
                float monto = Float.parseFloat(lblMonto.getText());
                obj = (Cliente) CCST.Eliminar(); //Me devuelve el primer cliente en la cola
                obj.setNumeroEntradas(Integer.parseInt(txtEntradas.getText()));
                obj.setTotalPagado(monto);
                ListaClientesST_Atendidos.adicionar(obj);
                JOptionPane.showMessageDialog(rootPane, "Cliente atendido");
                lblNombre.setText("");
                lblTarjeta.setText("");
                txtEntradas.setText("");
                lblMonto.setText("");
            } else {
                TCola CCCT = ColaClientesCT.consultar();
                txtEntradas.requestFocus();
                float monto = Float.parseFloat(lblMonto.getText());
                obj = (Cliente) CCCT.Eliminar();
                obj.setNumeroEntradas(Integer.parseInt(txtEntradas.getText()));
                obj.setTotalPagado(monto);
                ListaClientesCT_Atendidos.adicionar(obj);
                JOptionPane.showMessageDialog(rootPane, "Cliente atendido");
                lblNombre.setText("");
                lblTarjeta.setText("");
                txtEntradas.setText("");
                lblMonto.setText("");
            }
        }
        btnAtender.setEnabled(false);
    }//GEN-LAST:event_btnAtenderActionPerformed

    private void btnVerClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerClienteActionPerformed
        Cliente obj;

        if (cboTipoCola.getSelectedIndex() == 0) {
            TCola CCST = ColaClientesST.consultar();
            if (!CCST.Vacia()) {
                obj = (Cliente) CCST.Primero();
                lblNombre.setText(obj.getNombre());
                lblTarjeta.setText(obj.getTipoTarjeta());
            } else {
                JOptionPane.showMessageDialog(rootPane, "No hay clientes por atender en esta cola");
            }
        } else {
            TCola CCCT = ColaClientesCT.consultar();
            if (!CCCT.Vacia()) {
                obj = (Cliente) CCCT.Primero();
                lblNombre.setText(obj.getNombre());
                lblTarjeta.setText(obj.getTipoTarjeta());
            } else {
                JOptionPane.showMessageDialog(rootPane, "No hay clientes por atender en esta cola");
            }
        }
        txtEntradas.requestFocus();
    }//GEN-LAST:event_btnVerClienteActionPerformed

    private void txtEntradasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEntradasKeyTyped
        char c = evt.getKeyChar();

        if ((c < '0' | c > '9') | txtEntradas.getText().length() >= 3) {
            evt.consume();
        }
    }//GEN-LAST:event_txtEntradasKeyTyped

    private void txtEntradasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEntradasKeyReleased
        habilitarBtnAtender();
        habilitarBtn3puntos();
    }//GEN-LAST:event_txtEntradasKeyReleased

    private void txtEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntradasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtender;
    private javax.swing.JButton btnCalcularMonto;
    private javax.swing.JButton btnVerCliente;
    private javax.swing.JComboBox<String> cboTipoCola;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTarjeta;
    private javax.swing.JTextField txtEntradas;
    // End of variables declaration//GEN-END:variables
}
