package capaPresentacion;

import javax.swing.JFrame;

public class FrmMenuPrincipal extends javax.swing.JFrame {

    public FrmMenuPrincipal() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrin = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Cliente = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuItem03 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuItem05 = new javax.swing.JMenuItem();
        mnuItem06 = new javax.swing.JMenuItem();
        mnuItem07 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Tienda XYZ");

        panelPrin.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout panelPrinLayout = new javax.swing.GroupLayout(panelPrin);
        panelPrin.setLayout(panelPrinLayout);
        panelPrinLayout.setHorizontalGroup(
            panelPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelPrinLayout.setVerticalGroup(
            panelPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jMenu1.setText("Registro");

        Cliente.setText("Clientes");
        Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteActionPerformed(evt);
            }
        });
        jMenu1.add(Cliente);

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transacciones");

        mnuItem03.setText("Atender");
        mnuItem03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItem03ActionPerformed(evt);
            }
        });
        jMenu2.add(mnuItem03);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Reportes");

        mnuItem05.setText("ClientesGeneral");
        mnuItem05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItem05ActionPerformed(evt);
            }
        });
        jMenu3.add(mnuItem05);

        mnuItem06.setText("ClientesJuego");
        mnuItem06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItem06ActionPerformed(evt);
            }
        });
        jMenu3.add(mnuItem06);

        mnuItem07.setText("MontoRecaudadoPorJuego");
        mnuItem07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItem07ActionPerformed(evt);
            }
        });
        jMenu3.add(mnuItem07);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrin)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrin)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteActionPerformed
        FrmCliente objFrmIt01 = new FrmCliente();
        panelPrin.add(objFrmIt01);
        objFrmIt01.setVisible(true);
        objFrmIt01.moveToFront();
    }//GEN-LAST:event_ClienteActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed

    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuItem03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItem03ActionPerformed
        FrmAtender objFrmIt03 = new FrmAtender();
        panelPrin.add(objFrmIt03);
        objFrmIt03.setVisible(true);
        objFrmIt03.moveToFront();
    }//GEN-LAST:event_mnuItem03ActionPerformed

    private void mnuItem05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItem05ActionPerformed
        FrmClientesSinAtender objFrmIt05 = new FrmClientesSinAtender();
        panelPrin.add(objFrmIt05);
        objFrmIt05.setVisible(true);
        objFrmIt05.moveToFront();
    }//GEN-LAST:event_mnuItem05ActionPerformed

    private void mnuItem06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItem06ActionPerformed
        FrmClientesJuego objFrmIt06 = new FrmClientesJuego();
        panelPrin.add(objFrmIt06);
        objFrmIt06.setVisible(true);
        objFrmIt06.moveToFront();
    }//GEN-LAST:event_mnuItem06ActionPerformed

    private void mnuItem07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItem07ActionPerformed
        FrmMontoRecaudado objFrmIt07 = new FrmMontoRecaudado();
        panelPrin.add(objFrmIt07);
        objFrmIt07.setVisible(true);
        objFrmIt07.moveToFront();
    }//GEN-LAST:event_mnuItem07ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Cliente;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuItem03;
    private javax.swing.JMenuItem mnuItem05;
    private javax.swing.JMenuItem mnuItem06;
    private javax.swing.JMenuItem mnuItem07;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JDesktopPane panelPrin;
    // End of variables declaration//GEN-END:variables
}
