/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_Cliente;

import Capa_Logica.Proyecto;
import TListas.TLista;
import TListas.TListaEn;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class FrmReporteG extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmReporteG
     */
    public FrmReporteG() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        cboTipoEmpresa = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProyectos = new javax.swing.JTable();
        btnReporteD = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Dado el tipo de empresa, mostrar los proyectos que subvencionó los años 2020 y 2021.");

        jLabel3.setText("Tipo de empresa:");

        cboTipoEmpresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pública", "Privada" }));

        tblProyectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblProyectos);

        btnReporteD.setText("Listar");
        btnReporteD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(cboTipoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReporteD)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboTipoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReporteD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporteDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteDActionPerformed

        try {
            String tipo = cboTipoEmpresa.getSelectedItem().toString();

            DefaultTableModel modelo = new DefaultTableModel();

            modelo.addColumn("Codigo");
            modelo.addColumn("Nombre");
            modelo.addColumn("País");
            modelo.addColumn("Año de Inicio");
            modelo.addColumn("Meses de Duración");
            modelo.addColumn("Tipo");
            modelo.addColumn("Costo");

            Object[] datos = new Object[7];

            TLista lista = new TListaEn();
            lista = Proyecto.ProyPorTipoEmpresa20202021(tipo);
            for (int i = 0; i < lista.Cantidad(); i++) {
                Proyecto obj = (Proyecto) lista.Obtener(i);
                datos[0] = obj.getCodigo();
                datos[1] = obj.getNombre();
                datos[2] = obj.getPais();
                datos[3] = obj.getFechaInicio();
                datos[4] = obj.getDuracionMeses();
                datos[5] = obj.getTipo();
                datos[6] = obj.getCosto();
                modelo.addRow(datos);

            }
            tblProyectos.setModel(modelo);
        } catch (Exception ex) {
            Logger.getLogger(FrmReporteG.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnReporteDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReporteD;
    private javax.swing.JComboBox<String> cboTipoEmpresa;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProyectos;
    // End of variables declaration//GEN-END:variables
}
