/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Cliente;

import Data.Casa;
import Data.Departamento;
import Negocio.ArregloDeDepartamento;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jefer
 */
public class FrmListadoDepartamentos extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmListadoDepartamentos
     */
    public FrmListadoDepartamentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel24 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();

        setClosable(true);
        setTitle("Lista de departamentos disponibles");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("DEPARTAMENTOS DISPONIBLES");

        jButton4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton4.setText("Listar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setText("Listar menor");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setText("Listar mayor");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Habitaciones", "Ancho", "Largo", "Área", "Precio", "N° pisos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8)
                .addContainerGap())
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jButton4)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel modelo = new DefaultTableModel();
        
        modelo.addColumn("Código");
        modelo.addColumn("N° Hab.");
        modelo.addColumn("Ancho");
        modelo.addColumn("Largo");
        modelo.addColumn("Área");
        modelo.addColumn("Precio");
        modelo.addColumn("N° pisos");
        
        Object datos[] = new Object[7];
        
        Vector <Object> lista = ArregloDeDepartamento.consultar();
        
        for (int i = 0; i < lista.size(); i++) {
            Departamento obj = (Departamento)lista.get(i);
            datos[0]=obj.getCodigo();
            datos[1]=obj.getNumHab();
            datos[2]=obj.getAncho();
            datos[3]=obj.getLargo();
            datos[4]=obj.getArea();
            datos[5]=obj.getPrecio();
            datos[6]=obj.getNumPisos();
            modelo.addRow(datos);
        }
        tblDatos.setModel(modelo);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        DefaultTableModel modelo = new DefaultTableModel();
        
        modelo.addColumn("Código");
        modelo.addColumn("N° Hab.");
        modelo.addColumn("Ancho");
        modelo.addColumn("Largo");
        modelo.addColumn("Área");
        modelo.addColumn("Precio");
        modelo.addColumn("N° pisos");
        
        Object datos[] = new Object[7];
        
        Vector <Object> lista = ArregloDeDepartamento.precioMenor();
        
        for (int i = 0; i < lista.size(); i++) {
            Departamento obj = (Departamento)lista.get(i);
            datos[0]=obj.getCodigo();
            datos[1]=obj.getNumHab();
            datos[2]=obj.getAncho();
            datos[3]=obj.getLargo();
            datos[4]=obj.getArea();
            datos[5]=obj.getPrecio();
            datos[6]=obj.getNumPisos();
            modelo.addRow(datos);
        }
        tblDatos.setModel(modelo);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        DefaultTableModel modelo = new DefaultTableModel();
        
        modelo.addColumn("Código");
        modelo.addColumn("N° Hab.");
        modelo.addColumn("Ancho");
        modelo.addColumn("Largo");
        modelo.addColumn("Área");
        modelo.addColumn("Precio");
        modelo.addColumn("N° pisos");
        
        Object datos[] = new Object[7];
        
        Vector <Object> lista = ArregloDeDepartamento.precioMayor();
        
        for (int i = 0; i < lista.size(); i++) {
            Departamento obj = (Departamento)lista.get(i);
            datos[0]=obj.getCodigo();
            datos[1]=obj.getNumHab();
            datos[2]=obj.getAncho();
            datos[3]=obj.getLargo();
            datos[4]=obj.getArea();
            datos[5]=obj.getPrecio();
            datos[6]=obj.getNumPisos();
            modelo.addRow(datos);
        }
        tblDatos.setModel(modelo);
    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDatos;
    // End of variables declaration//GEN-END:variables
}
