/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Capa_Cliente;

import Capa_Negocio.Producto;
import TListas.TLista;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jefer
 */
public class FrmProductoConMayorProduccion extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmProductoConMayorProduccion
     */
    public FrmProductoConMayorProduccion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnProductoMayor = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Producto con mayor producción");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnProductoMayor.setText("Mostrar");
        btnProductoMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoMayorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProductoMayor)
                .addGap(214, 214, 214))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProductoMayor)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductoMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoMayorActionPerformed
        DefaultTableModel modelo = new DefaultTableModel();
        
        
        modelo.addColumn("Código");
        modelo.addColumn("Nombre");
        modelo.addColumn("Tipo");
        modelo.addColumn("Producción");
        modelo.addColumn("Lote");
        modelo.addColumn("Costo (por Kg)");
        
        Object datos[] = new Object[6];
        
        TLista lista = Producto.ProductoConMayorProduccion();
        
        for (int i = 0; i < lista.Cantidad(); i++) {
            Producto objProducto = (Producto) lista.Obtener(i);
            datos[0]=objProducto.getCodigo();
            datos[1]=objProducto.getNombreProducto();
            datos[2]=objProducto.getTipoProducto();
            datos[3]=objProducto.getCantProduccion();
            datos[4]=objProducto.getLote();
            datos[5]=objProducto.getCostoPorKg();
            modelo.addRow(datos);
        }
        jTable1.setModel(modelo);
    }//GEN-LAST:event_btnProductoMayorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProductoMayor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
