/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Cliente;

import TColas.*;
import Logica.Cliente;
import Datos.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FrmMostrarColas extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmMostrarColas
     */
    public FrmMostrarColas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSuperman = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHulk = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblThor = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Colas disponibles");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Cola \"Hulk\"");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Cola \"Superman\"");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Cola \"Thor\"");

        tblSuperman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblSuperman);

        tblHulk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblHulk);

        tblThor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tblThor);

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton1.setText("LISTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel1)
                .addGap(233, 233, 233)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(130, 130, 130))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(429, 429, 429))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Cliente obj = new Cliente();

        TCola colaH = ColaHulk.consultar();
        TCola colaS = ColaSuperman.consultar();
        TCola colaT = ColaThor.consultar();

        if (colaH.Vacia()) {
            JOptionPane.showMessageDialog(rootPane, "Cola Hulk vacía");
        } else {
            DefaultTableModel modeloH = new DefaultTableModel(); //Tabla para la cola Hulk
            modeloH.addColumn("Nombre");
            modeloH.addColumn("Sexo");
            modeloH.addColumn("Costo");

            Object datosH[] = new Object[3];

            for (int i = 0; i < colaH.Cantidad(); i++) {
                obj = (Cliente) colaH.Obtener(i);
                datosH[0] = obj.getNombre();
                datosH[1] = obj.getSexo();
                datosH[2] = obj.getCostoEntrada();
                modeloH.addRow(datosH);
            }
            tblHulk.setModel(modeloH);
        }
        if (colaS.Vacia()) {
            JOptionPane.showMessageDialog(rootPane, "Cola Superman vacía");
        } else {
            DefaultTableModel modeloS = new DefaultTableModel(); //Tabla para la cola Superman
            modeloS.addColumn("Nombre");
            modeloS.addColumn("Sexo");
            modeloS.addColumn("Costo");

            Object datosS[] = new Object[3];

            for (int i = 0; i < colaS.Cantidad(); i++) {
                obj = (Cliente) colaS.Obtener(i);
                datosS[0] = obj.getNombre();
                datosS[1] = obj.getSexo();
                datosS[2] = obj.getCostoEntrada();
                modeloS.addRow(datosS);
            }
            tblSuperman.setModel(modeloS);
        }
        if (colaT.Vacia()) {
            JOptionPane.showMessageDialog(rootPane, "Cola Thor vacía");
        } else {
            DefaultTableModel modeloT = new DefaultTableModel(); //Tabla para la cola Thor
            modeloT.addColumn("Nombre");
            modeloT.addColumn("Sexo");
            modeloT.addColumn("Costo");

            Object datosT[] = new Object[3];

            for (int i = 0; i < colaT.Cantidad(); i++) {
                obj = (Cliente) colaT.Obtener(i);
                datosT[0] = obj.getNombre();
                datosT[1] = obj.getSexo();
                datosT[2] = obj.getCostoEntrada();
                modeloT.addRow(datosT);
            }
            tblThor.setModel(modeloT);
        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblHulk;
    private javax.swing.JTable tblSuperman;
    private javax.swing.JTable tblThor;
    // End of variables declaration//GEN-END:variables
}
