/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_Cliente;

import Capa_Logica.Ciudad;
import TPilas.TPila;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Franko
 */
public class FrmDesapilarCiudades extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmDesapilarCiudades
     */
    public FrmDesapilarCiudades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreProceso = new javax.swing.JLabel();
        lblTiempoProceso = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblTiempo = new javax.swing.JLabel();
        cmdExtraer = new javax.swing.JButton();
        cmdCerrar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Extraer Ciudades");

        lblNombre.setText("Nombre del Proceso: ");

        lblTiempo.setText("Tiempo:");

        cmdExtraer.setText("Extraer");
        cmdExtraer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdExtraerActionPerformed(evt);
            }
        });

        cmdCerrar.setText("Cerrar");
        cmdCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblTiempo))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTiempoProceso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombreProceso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdExtraer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdCerrar)
                        .addGap(85, 85, 85))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblNombreProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblTiempoProceso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTiempo))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdExtraer)
                    .addComponent(cmdCerrar))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdExtraerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdExtraerActionPerformed

        Ciudad objCiudad = null;
        TPila Pila=null;
        try {
            Pila = Ciudad.ConsultarTodo();
        } catch (Exception ex) {
            Logger.getLogger(FrmDesapilarCiudades.class.getName()).log(Level.SEVERE, null, ex);
        }

        if(!Pila.Vacia())//Validamos que la pila no esté vacía
        {
            try {
                objCiudad = (Ciudad) Ciudad.Extraer();
            } catch (Exception ex) {
                Logger.getLogger(FrmDesapilarCiudades.class.getName()).log(Level.SEVERE, null, ex);
            }
            lblNombreProceso.setText(objCiudad.getNombre());
            lblTiempoProceso.setText(String.valueOf(objCiudad.getTiempoPermanencia()));
        }
        else
        JOptionPane.showMessageDialog(this, "PILA Vacía", "Error", 2);

    }//GEN-LAST:event_cmdExtraerActionPerformed

    private void cmdCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_cmdCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCerrar;
    private javax.swing.JButton cmdExtraer;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreProceso;
    private javax.swing.JLabel lblTiempo;
    private javax.swing.JLabel lblTiempoProceso;
    // End of variables declaration//GEN-END:variables
}
